from nexus.config import NexusConfig, get_settings, configure
from nexus.errors import (
    NexusError,
    ConfigError,
    DatabaseError,
    AuthError,
    NotFoundError,
    ValidationError,
    ExternalServiceError,
    RateLimitError,
    ForbiddenError,
    ConflictError,
)
from nexus.context import (
    set_request_context,
    get_request_id,
    get_user_id,
    get_trace_id,
    new_request_id,
    clear_request_context,
    RequestContext,
)
from nexus.database import DatabaseManager, get_db, db_manager, Base, init_db, close_db
from nexus.logging import setup_logging, setup_loguru, get_logger
from nexus.response import (
    ApiResponse,
    PaginatedResponse,
    PaginationMeta,
    success_response,
    error_response,
    paginate_response,
)
from nexus.utils import (
    TimeUtils,
    MemoryCache,
    cached,
    HttpClient,
    HealthRegistry,
    cosine_similarity,
    batch_cosine_similarity,
    clamp,
    safe_float,
    safe_int,
    safe_bool,
    paginate_from_skip,
)
from nexus.middleware import (
    setup_cors,
    RequestIdMiddleware,
    NoCacheMiddleware,
    LoggingMiddleware,
    ErrorHandlerMiddleware,
    ServiceAuthMiddleware,
    setup_exception_handlers,
    REQUEST_ID_HEADER,
)
from nexus.rate_limit import RateLimitMiddleware
from nexus.config import RateLimitConfig as RateLimitConfig
from nexus.auth import (
    AuthDependencies,
    get_current_user_id_required,
    get_current_user_id_optional,
    get_current_user_id_int,
    get_current_user_full,
    get_current_user_full_normalized,
    normalize_user_dict,
    get_user_string_id,
    parse_user_id,
    configure_uc_sdk,
    extract_bearer_token,
)
from nexus.auth_routes import create_auth_router
from nexus.uc_sdk_helper import (
    init_uc_sdk,
    init_uc_sdk_from_lion,
    get_uc_sdk,
    close_uc_sdk,
    standard_ok,
    standard_err,
)
from nexus.repository import BaseRepository, StatelessRepository
from nexus.service import BaseService
from nexus.api_decorators import handle_api_errors
from nexus.lion import (
    LionIntegration,
    get_lion,
    get_chat_config,
    get_embed_config,
    get_image_config,
    get_infra_config,
    get_business_config,
    clear_lion_cache,
)
from nexus.infra import (
    get_uc_base_url,
    get_uc_config,
    get_spider_base_url,
    get_spider_config,
    get_promptmanager_config,
    get_beememory_base_url,
    get_chroma_config,
    get_rate_limit_config,
    get_retry_config,
    get_timeout_config,
    get_auth_config,
    get_llm_quota_config,
)
from nexus.fastapi_setup import (
    create_app,
    setup_static_files,
    setup_health_check,
    register_internal_endpoints,
    AppLifecycle,
)
from nexus.llm_utils import (
    parse_llm_json,
    find_balanced_json,
    with_retry,
    strip_code_fence,
    LLMTimeoutError,
)
from nexus.llm import (
    LLMService,
    get_llm_service,
    configure_ironman,
    mark_ironman_configured,
)
from nexus.ironman import (
    init_ironman,
    default_config_loader,
    get_bootstrap,
    is_ironman_available,
    get_init_app_name,
)
from nexus.web_search import WebSearchService, get_web_search_service
from nexus.deep_research import DeepResearchService, get_deep_research_service
from nexus.dialogue_history import (
    HistoryStrategy,
    HistoryStore,
    InMemoryStore,
    SQLiteStore,
    ConversationHistory,
    get_history,
    clear_history_cache,
)
from nexus.streaming import (
    sse_event,
    sse_chat_stream,
    chunked_text_stream,
)
from nexus.circuit_breaker import (
    CircuitBreaker,
    CircuitBreakerConfig,
    CircuitState,
    CircuitMetrics,
    CircuitBreakerOpenError,
    get_circuit_breaker,
    get_llm_circuit,
)
from nexus.cost_guard import (
    CostGuard,
    CostBudget,
    BudgetPeriod,
    TokenUsage,
    CostBudgetExceededError,
    get_cost_guard,
    configure_pricing,
)
from nexus.llm_rate_limiter import (
    LLMRateLimiter,
    get_llm_rate_limiter,
)
from nexus.resilient_llm import resilient_ask

__version__ = "1.10.0"

__all__ = [
    "__version__",
    "NexusConfig",
    "get_settings",
    "configure",
    "NexusError",
    "ConfigError",
    "DatabaseError",
    "AuthError",
    "NotFoundError",
    "ValidationError",
    "ExternalServiceError",
    "RateLimitError",
    "ForbiddenError",
    "ConflictError",
    "set_request_context",
    "get_request_id",
    "get_user_id",
    "get_trace_id",
    "new_request_id",
    "clear_request_context",
    "RequestContext",
    "DatabaseManager",
    "get_db",
    "db_manager",
    "Base",
    "init_db",
    "close_db",
    "setup_logging",
    "setup_loguru",
    "get_logger",
    "ApiResponse",
    "PaginatedResponse",
    "PaginationMeta",
    "success_response",
    "error_response",
    "paginate_response",
    "TimeUtils",
    "MemoryCache",
    "cached",
    "HttpClient",
    "HealthRegistry",
    "cosine_similarity",
    "batch_cosine_similarity",
    "clamp",
    "safe_float",
    "safe_int",
    "safe_bool",
    "paginate_from_skip",
    "setup_cors",
    "RequestIdMiddleware",
    "NoCacheMiddleware",
    "LoggingMiddleware",
    "ErrorHandlerMiddleware",
    "ServiceAuthMiddleware",
    "setup_exception_handlers",
    "REQUEST_ID_HEADER",
    "RateLimitMiddleware",
    "RateLimitConfig",
    "AuthDependencies",
    "get_current_user_id_required",
    "get_current_user_id_optional",
    "get_current_user_id_int",
    "get_current_user_full",
    "get_current_user_full_normalized",
    "normalize_user_dict",
    "get_user_string_id",
    "parse_user_id",
    "create_auth_router",
    "init_uc_sdk",
    "init_uc_sdk_from_lion",
    "get_uc_sdk",
    "close_uc_sdk",
    "configure_uc_sdk",
    "extract_bearer_token",
    "standard_ok",
    "standard_err",
    "BaseRepository",
    "StatelessRepository",
    "BaseService",
    "handle_api_errors",
    "LionIntegration",
    "get_lion",
    "get_chat_config",
    "get_embed_config",
    "get_image_config",
    "get_infra_config",
    "get_business_config",
    "clear_lion_cache",
    "get_uc_base_url",
    "get_uc_config",
    "get_spider_base_url",
    "get_spider_config",
    "get_promptmanager_config",
    "get_beememory_base_url",
    "get_chroma_config",
    "get_rate_limit_config",
    "get_retry_config",
    "get_timeout_config",
    "get_auth_config",
    "get_llm_quota_config",
    "create_app",
    "setup_static_files",
    "setup_health_check",
    "register_internal_endpoints",
    "AppLifecycle",
    "parse_llm_json",
    "find_balanced_json",
    "with_retry",
    "strip_code_fence",
    "LLMTimeoutError",
    "LLMService",
    "get_llm_service",
    "configure_ironman",
    "mark_ironman_configured",
    "init_ironman",
    "default_config_loader",
    "get_bootstrap",
    "is_ironman_available",
    "get_init_app_name",
    "WebSearchService",
    "get_web_search_service",
    "DeepResearchService",
    "get_deep_research_service",
    "HistoryStrategy",
    "HistoryStore",
    "InMemoryStore",
    "SQLiteStore",
    "ConversationHistory",
    "get_history",
    "clear_history_cache",
    "sse_event",
    "sse_chat_stream",
    "chunked_text_stream",
    "SSEManager",
    "SSEConnectionError",
    "sse_event_generator",
    "NotificationChannel",
    "VALID_CHANNELS",
    "WebhookChannel",
    "ChannelDispatcher",
    "CircuitBreaker",
    "CircuitBreakerConfig",
    "CircuitState",
    "CircuitMetrics",
    "CircuitBreakerOpenError",
    "get_circuit_breaker",
    "get_llm_circuit",
    "CostGuard",
    "CostBudget",
    "BudgetPeriod",
    "TokenUsage",
    "CostBudgetExceededError",
    "get_cost_guard",
    "configure_pricing",
    "LLMRateLimiter",
    "get_llm_rate_limiter",
    "resilient_ask",
]
